openapi: 3.0.1
info:
  title: Basic authentification with Bearer Keys
  version: '1.0'
servers:
- url: /
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: UUID
paths:
  /fib:
    get:
      description: Calculates Fibonacci number
      parameters:
      - name: 'n'
        description: x for Fibonnacci number
        in: query
        schema:
          type: integer
        example: 10
        required: yes
      security:
      - bearerAuth: []
      responses:
        '200':
          description: API response
          content:
            text/plain:
              schema:
                type: string
                example: 5
        '401':
          description: Not authorized
          content:
            text/plain:
              schema:
                type: string
                example: API key is missing
